heroBattle/project/heroes/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	Leader_Login,
	index_view,
	logout_view,
	SignUp_View
)

urlpatterns=[
	url(r'^login/$', Leader_Login.as_view(), name="login"),
	url(r'^logout/$', logout_view, name="logout"),
	url(r'^signup/$', SignUp_View.as_view(), name="signup"),
	url(r'^$', index_view, name="index")
]

heroBattle/project/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [	
    url(r'^admin/', admin.site.urls),
    url(r'^heroes/', include("heroes.urls", namespace="heroes")),
]

heroBattle/project/heroes/models.py
from django.db import models
from django.contrib.auth.models import User

# added default blank for bio. "Blank will appear in the text field on the sign up page"
class Leader(models.Model):
	user = models.OneToOneField(User)
	first_name = models.CharField(max_length=40)
	last_name = models.CharField(max_length=40)
	bio = models.TextField(max_length=500, default='blank')
	hero_name = models.CharField(max_length=40, default = "blank")
	age = models.PositiveSmallIntegerField(default = 0)

	def __str__(self):
		return self.user.username
	

class Power(models.Model):
	name = models.CharField(max_length=40)
	method = models.CharField(max_length=40)
	description = models.TextField(max_length=500, default='blank')
	leader = models.ManyToManyField(Leader)

	def __str__(self):
		return self.name

heroBattle/project/heroes/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Leader
from django.core.validators import RegexValidator

class UserSignUp(forms.ModelForm):
	
	# Validator Jeff Made in case you want to add it
	alphanumeric = RegexValidator(r'^[0-9a-zA-Z_]*$',
		'This value may contain only letters, '
		'numbers and _ characters.')

	# Had to set up this empty string so that bullshit default helptext doesn't appear. Thanks Django
	username = forms.CharField(widget=forms.TextInput(
		),
		help_text="",
		required = True,
		min_length = 6,
	)
	password = forms.CharField(widget=forms.PasswordInput(),
		required = True,
		min_length = 6,
		validators=[alphanumeric]
	)

	class Meta:
		model = User
		fields = [
			"username",
			"password",
		]

class LeaderSignUp(forms.ModelForm):

	class Meta:
		model = Leader
		fields = [
			"first_name",
			"last_name",
			"bio",
		]

heroBattle/project/heroes/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Leader, Power
from django.contrib.auth.models import User
from django.views.generic import View
from django import forms
from django.contrib.auth import authenticate, login, logout
from .forms import LeaderSignUp, UserSignUp
from django.contrib.auth.hashers import make_password


def index_view(request):
	# user == "AnonymousUser" unless they already logged in. Then it will be the username
	user = request.user
	print(user)

	if user.is_authenticated():

		# grab the User object and use it to grab the Leader object
		profile = User.objects.get(username=user)
		leader = Leader.objects.get(user = profile)
		power = Power.objects.all()
		context = {
			"profile" : profile,
			"leader": leader,
			"power": power
		}		
		return render(request, 'heroes/leader.html', context)
	else:
		return render(request, 'base.html', {})

def logout_view(request):
	logout(request)
	return redirect('heroes:index')

class SignUp_View(View):
	# made two model forms for the sign up page. One for the Django User and the other for our Leader model
	user_form = UserSignUp
	leader_form = LeaderSignUp
	initial = {'key': 'value'}

	# GET request that will pass the forms to the signup html
	def get(self, request, *args, **kwargs):
		l_signup_form = self.leader_form(initial=self.initial)
		u_signup_form = self.user_form(initial=self.initial)
		context = {
			"leader": l_signup_form,
			"user" : u_signup_form
		}
		return render(request, 'heroes/signup.html', context)

	def post(self,request,*args, **kwargs):

		# Take the form information
		user_submit_form = self.user_form(request.POST or None)
		leader_submit_form = self.leader_form(request.POST or None)
		
		# check if both are valid
		if user_submit_form.is_valid() and leader_submit_form.is_valid():
			
			# cleaned data allows us to target a tag from the form through it's "name" and it will return the value
			leader_first_name = leader_submit_form.cleaned_data['first_name']
			leader_last_name = leader_submit_form.cleaned_data['last_name']
			leader_bio = leader_submit_form.cleaned_data['bio']

			# target the user instance from the form submit
			user_instance = user_submit_form.save(commit=False)

			# hash the password being generated
			user_instance.password = make_password(user_submit_form.cleaned_data['password'])

			# save the user. Must do this before we can attach the leader
			user_instance.save()

			# create the leader instance and save it
			leader_instance = Leader(
				user=user_instance, 
				first_name = leader_first_name,
				last_name = leader_last_name,
				bio = leader_bio
				)

			# save leader
			leader_instance.save()

			# if all this saves properly we redirect to the home page so they could log in
			return redirect('heroes:index')

		else: 
			# need to fix what happens when they enter bad information
			return HttpResponse("The information you entered was not valid")

class Leader_Login(View):

# Do not need to pass in "*args, **kwargs" into the method parameters
# Not using model forms for Django User Model b/c it's fucking dumb

	def get(self, request):
		return render(request, 'heroes/login.html', {})

# Django auth comes with the authenticate and login methods
	def post(self, request):
		# username = request.POST.get('username')
		# password = request.POST.get('password')
		username = request.POST['username']
		password = request.POST['password']
		print(username)
		print(password)

		# authenticates returns True or None
		user = authenticate(username=username, password=password)

		print(user)
		if user:
			if user.is_active:
				login(request, user)
				return redirect('heroes:index')

		# decide on what you want to do if the log in fails
		elif user == None:
			return HttpResponse("The Authentication method did not pass")

heroBattle/project/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="{% static 'materialize/materialize.min.css' %}">
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<title>BASENESS</title>
	<script src="{% static 'jquery-2.2.3.min.js' %}"></script>
	<script src="{% static 'materialize/materialize.min.js' %}"></script>
	<script src="{% static 'main.js' %}"></script>
</head>
<body>

	<nav>
    <div class="nav-wrapper">
      <a href="{% url 'heroes:index' %}" class="brand-logo">Heroes</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="{% url 'heroes:login' %}">Login</a></li>
        <li><a href="{% url 'heroes:signup' %}">Sign Up</a></li>
        <li><a href="badges.html">Power List</a></li>
        <li><a href="{% url 'heroes:logout' %}">Log Out</a></li>
      </ul>
    </div>
  </nav>

	<div class='container'>
		{% block content %}

			<div class="row">
				<div class="col 6 offset-s3">

					<div class="row">
						<div class="col s12 m12">
							<div class="card blue-grey darken-1">
								<div class="card-content white-text">
									<p class="card-title">Hero Shizzzz</p>
										<p>Create a user profile. Then start building your own super hero from scratch!</p>
								</div>
							<div class="card-action">
								<a href="{% url 'heroes:login' %}">Log In</a>
								<a href="{% url 'heroes:signup' %}">Register</a>
							</div>
							</div>
						</div>
					</div>

				</div>
			</div>
				
		{% endblock content %}
	</div>

</body>
</html>